Added support for setting and changing reminder due date and time
DamascenoRafael/reminders-menubar pull request #80
Opened 2022-10-08 19:07 UTC by andylin2004

A previous issue discussed about adding the intelligent date and time setter like in the reminders app (see https://github.com/DamascenoRafael/reminders-menubar/issues/17). This is a partial solution to that issue where users can change and set reminder due date and time manually (either below the textfield or via a popover that will apply changes once the user clicks out of the popover). English localization has also been applied for this.

2022-10-19 23:45 UTC, zydeico requested changes
LGTM but, delete changes in the **.pbxproj** file

2022-10-19 23:45 UTC, zydeico commented on reminders-menu-bar.xcodeproj/project.pbxproj
> +				DEVELOPMENT_TEAM = QW3PB89WQ9;
Delete changes in this file

2022-10-20 00:08 UTC, zydeico approved these changes

2022-10-20 00:09 UTC, zydeico approved these changes
LGTM

2022-10-20 03:57 UTC, DamascenoRafael commented
Thanks for your contribution @andylin2004!
I know you've done a previous PR related to this, sorry I didn't look at this sooner, time is almost always short.

My macbook stopped turning on after an update, so I won't be able to show what I was doing and test your changes now. 
But as soon as I fix it I'll look into it.

Two small observations:
- Can you revert changes to Package.resolved? This file refers to a dependency needed by another feature.
- Can you install [SwiftLint](https://github.com/realm/SwiftLint)? After installing when building the project it will display warnings regarding code style. We don't need to solve all warnings, some can be ignored, but in general the idea is to try to follow some styles.

2022-10-20 04:12 UTC, andylin2004 commented
> Thanks for your contribution @andylin2004! I know you've done a previous PR related to this, sorry I didn't look at this sooner, time is almost always short.
> 
> My macbook stopped turning on after an update, so I won't be able to show what I was doing and test your changes now. But as soon as I fix it I'll look into it.
> 
> Two small observations:
> 
> * Can you revert changes to Package.resolved? This file refers to a dependency needed by another feature.
> * Can you install [SwiftLint](https://github.com/realm/SwiftLint)? After installing when building the project it will display warnings regarding code style. We don't need to solve all warnings, some can be ignored, but in general the idea is to try to follow some styles.

I have installed SwiftLint and adjusted my code to conform to the proper code style. Package.resolved isn't being tracked, so I think Xcode is autogenerating that.

2022-10-29 19:08 UTC, DamascenoRafael commented
Hi, @andylin2004. I finally got my mac back.

The `Package.resolved` file is tracked, but you deleted it in your branch.
You can run the git command below to restore the master file to your branch:

```
git checkout origin/master reminders-menu-bar.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
```

I was working on an edit popover (similar to the one in Apple Reminders) allowing to edit the reminder's title, notes, date/time and priority.

<img width="773" alt="Screenshot 2022-10-29 at 15 38 10" src="https://user-images.githubusercontent.com/9842644/198848242-7e660b16-fbcf-4691-8908-c48b9eecde92.png">

My idea is to combine this work (from the image above) with the possibility you created to add date/time when creating a reminder (image below). Sound good to you?

<img width="474" alt="image" src="https://user-images.githubusercontent.com/9842644/198848737-972abcf9-a28f-4836-b493-2afb9d17bfaa.png">


If it's ok I will merge your branch into a separate branch to combine these works and release this feature soon.

2022-10-29 19:33 UTC, andylin2004 commented
Sounds good! The initial version did have that, but I thought that was problematic because multiple popovers would then be needed.

2022-10-30 03:02 UTC, merged

2022-10-31 03:00 UTC, DamascenoRafael commented
@andylin2004 can you please explain to me the advantage of using the `LegacyReminderTitleTextFieldView` instead of the default TextField in macOS versions below 12.0 (before macOS Monterey)?

2022-10-31 12:50 UTC, andylin2004 commented
The default textfield on macOS 11 will automatically create a reminder with the text in the textbook as the reminder name when the cursor clicks on the add date button (which is what we don't want to do, because people will probably adjust the due date multiple times).

```LegacyReminderTitleTextFieldView``` basically fixes this issue by expecting an enter key to be hit before the contents of the textbook is used to create a reminder

2022-11-01 02:00 UTC, DamascenoRafael commented
Great! Thanks for the clarification. Didn't know about these behaviors on Big Sur.